apiVersion: v1
kind: Service
metadata:
  name: voting-app-result
spec:
  type: NodePort
  ports:
    - name: 'voting-app-result-service'
      port: 5001
      targetPort: 80
      nodePort: 31001
  selector:
    app: voting-app-result
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-result-external
spec:
  type: LoadBalancer
  ports:
    - name: 'voting-app-result-service'
      port: 8001
      targetPort: 80
  selector:
    app: voting-app-result
