apiVersion: v1
kind: Service
metadata:
  name: ui-angularapp-svc
  labels:
    run: ui-angularapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    run: ui-angularapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui-angularapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: ui-angularapp
    spec:
      containers:
        - name: ui-angularapp
          image: gcr.io/sandbox-228621/ui-angularapp
          ports:
            - containerPort: 80
            - containerPort: 443
